---
- hosts: dev
  tasks:
    - name: Ping before reboot
      ping:
    - shell: "sleep 5 && reboot"
      async: 1
      poll: 0
    - name: Wait for system to become reachable
      wait_for_connection:
        delay: 5
        timeout: 300
        connect_timeout: 20
        sleep: 5
    - name: Ping after reboot
      ping:
